export const DEFAULT_EXERCISES = [
  { name: 'Bench Press', muscle_group: 'Chest', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 6, rep_range_max: 10 },
  { name: 'Incline Dumbbell Press', muscle_group: 'Chest', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 8, rep_range_max: 12 },
  { name: 'Cable Fly', muscle_group: 'Chest', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 12, rep_range_max: 15 },
  { name: 'Chest Dip', muscle_group: 'Chest', progression_type: 'rep_first', is_bodyweight: true, rep_range_min: 8, rep_range_max: 15 },
  { name: 'Pull Ups', muscle_group: 'Back', progression_type: 'rep_first', is_bodyweight: true, rep_range_min: 6, rep_range_max: 12 },
  { name: 'Lat Pulldown', muscle_group: 'Back', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 8, rep_range_max: 12 },
  { name: 'Seated Cable Row', muscle_group: 'Back', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 8, rep_range_max: 12 },
  { name: 'Barbell Row', muscle_group: 'Back', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 6, rep_range_max: 10 },
  { name: 'Single Arm Dumbbell Row', muscle_group: 'Back', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 8, rep_range_max: 12 },
  { name: 'Shoulder Press', muscle_group: 'Shoulders', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 8, rep_range_max: 12 },
  { name: 'Lateral Raise', muscle_group: 'Shoulders', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 12, rep_range_max: 15 },
  { name: 'Face Pull', muscle_group: 'Shoulders', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 12, rep_range_max: 15 },
  { name: 'Squat', muscle_group: 'Legs', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 6, rep_range_max: 10 },
  { name: 'Leg Press', muscle_group: 'Legs', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 8, rep_range_max: 12 },
  { name: 'Romanian Deadlift', muscle_group: 'Legs', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 8, rep_range_max: 12 },
  { name: 'Leg Curl', muscle_group: 'Legs', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 10, rep_range_max: 15 },
  { name: 'Leg Extension', muscle_group: 'Legs', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 10, rep_range_max: 15 },
  { name: 'Calf Raise', muscle_group: 'Legs', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 12, rep_range_max: 20 },
  { name: 'Bicep Curl', muscle_group: 'Biceps', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 10, rep_range_max: 15 },
  { name: 'Hammer Curl', muscle_group: 'Biceps', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 10, rep_range_max: 15 },
  { name: 'Incline Curl', muscle_group: 'Biceps', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 10, rep_range_max: 15 },
  { name: 'Tricep Pushdown', muscle_group: 'Triceps', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 10, rep_range_max: 15 },
  { name: 'Overhead Tricep Extension', muscle_group: 'Triceps', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 10, rep_range_max: 15 },
  { name: 'Skull Crusher', muscle_group: 'Triceps', progression_type: 'double_progression', is_bodyweight: false, rep_range_min: 8, rep_range_max: 12 },
] as const
